Switch to search area with outline
ResonantGeoData/RGD-Vue pull request #72
Opened 2022-01-14 22:31 UTC by annehaley

Resolves #59

2022-01-17 15:33 UTC, banesullivan approved these changes

2022-01-17 17:17 UTC, marySalvi commented
https://github.com/ResonantGeoData/RGD-Vue/blob/ea6739cd18bca00c9f737288fcccbca81bb9e8de/src/components/organisms/CesiumViewer.vue#L324

This will also need to change so that the shape specified by user input is an outline as well:
`      cesiumViewer.value.entities.add({
        polygon: {
          hierarchy: uploadedFootprint,
          outline: true,
          outlineColor: Cesium.Color.RED,
          outlineWidth: 3,
          fill: false,
        },
      });`
      
      This should work

2022-01-17 17:20 UTC, marySalvi requested changes
https://github.com/ResonantGeoData/RGD-Vue/blob/ea6739cd18bca00c9f737288fcccbca81bb9e8de/src/components/organisms/CesiumViewer.vue#L324

This will also need to change so that the shape specified by user input is an outline as well. This should work:
```
   cesiumViewer.value.entities.add({
        polygon: {
          hierarchy: uploadedFootprint,
          outline: true,
          outlineColor: Cesium.Color.RED,
          outlineWidth: 3,
          fill: false,
        },
      });
```

2022-01-18 04:12 UTC, marySalvi approved these changes

2022-01-18 04:14 UTC, merged